.MODEL SMALL
.STACK 100H
.DATA
    ARRAY DW 1,2,3,4,5,6,7,8,9,19
    SIZE EQU 10
    MSG1 DB 'The largest number is: $'
    NEWLINE DB 0DH, 0AH, '$'
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    MOV SP, 100H

    LEA SI, ARRAY
    MOV CX, SIZE
PUSH_LOOP:
    MOV AX, [SI]
    PUSH AX
    ADD SI, 2
    LOOP PUSH_LOOP
    POP AX
    MOV BX, AX

    MOV CX, SIZE - 1
FIND_LARGEST:
    POP AX
    CMP AX, BX
    JLE CONTINUE
    MOV BX, AX
CONTINUE:
    LOOP FIND_LARGEST

    LEA DX, MSG1
    MOV AH, 09H
    INT 21H
    MOV AX, BX
    CALL DISPLAY_NUMBER
    LEA DX, NEWLINE
    MOV AH, 09H
    INT 21H
    MOV AH, 4CH
    INT 21H
MAIN ENDP

DISPLAY_NUMBER PROC
    MOV BX, 10
    MOV CX, 0
CONVERT_LOOP:
    MOV DX, 0
    DIV BX
    ADD DL, '0'
    PUSH DX
    INC CX
    CMP AX, 0
    JNE CONVERT_LOOP
DISPLAY_LOOP:
    POP DX
    MOV AH, 02H
    INT 21H
    LOOP DISPLAY_LOOP
    RET
DISPLAY_NUMBER ENDP
END MAIN
